### PR TITLE
Set up continuous deployment

### LINKED ISSUE #15: Add CircleCI configuration and deployment to AWS
This should match the process that chop-dbhi/data-models-sqlalchemy has.

### PR DESCRIPTION
**Pull request by gracecodes144**
Fixes #15

Signed-off-by: Aaron Browne aaron0browne@gmail.com

Still testing and adding comments, but it's going well. I'll comment when ready for merge.

### CODE REVIEW

**Comment by bruth** [comment]
Wicked.

**Comment by gracecodes144** [comment]
Of course, we're already running into the EIP limit on AWS...

**Comment by gracecodes144** [comment]
OK, ready for merge from my perspective. We're not going to get a successful AWS instance build to do user testing against on the branch due to the EIP restriction and I'm not going to figure out a different deploy mechanism today.

@bruth, you should review the changes I made to `Makefile`, `main.go`, and `version.go`. The summary is:
- Select first GOPATH entry for Makefile purposes.
- Pass `progReleaseNum` from an environment variable via the Makefile.
- Remove release level and pre-release information from final releases.
- Add a `-version` flag to the application that prints the version and exits.

**Comment by bruth** [comment]
Great work!

**Pull request merged**
