### PR TITLE
Remove deploy configuration

### LINKED ISSUE #33: Document Terraform deployment

### PR DESCRIPTION
**Pull request by gracecodes144**
Fixes #33 

Signed-off-by: Aaron Browne <aaron0browne@gmail.com>

### CODE REVIEW

**Comment by bruth** [comment]
Since a terraform config/state is environment specific, do you think it is necessary/appropriate to include it in this public repo? Or should we maintain it in a private one (or internal GH)?

Also `bindata.go` should be recreated on every build. It only needs to be updated after the static assets are modified. That was my mistake with adding it as a dependency on the build target.

**Comment by bruth** [comment]
I realize I am late to game with saying this since the files were committed a while ago.

**Comment by gracecodes144** [comment]
Oh yeah, good point, I guess it does make sense to separate them. Migrating to internal GitHub makes the most sense to me, that OK with you?

Re `bindata.go`, I will remove the references to rebuilding it. I had run into a problem with it while building the image previously, but I think that must have been because I ran `make build` before, which created a locally-linked file.

**Comment by bruth** [comment]
Yes that sounds good. re: `bindata.go`, unless a dev build is created which creates a local reference to files on disk (as you observed), there is no need to rebuild it. The local diff would be obvious and it would just be a matter of ensuring a production build is made before committing and/or building a new binary.

**Comment by gracecodes144** [comment]
For posterity, the CHOP specific deployment configuration is now on the internal GitHub [here](https://github.research.chop.edu/devops/data-models-service).

**Pull request merged**
