### PR TITLE
Fix CI/CD bugs

### LINKED ISSUE #24: Bug in CI/CD
First, tests are being run against the legacy `dbhi/data-models` image pulled from docker hub. Second, AWS needs to know that the port is 8123, not 80.

### PR DESCRIPTION
**Pull request by gracecodes144**
Fixes #24

Signed-off-by: Aaron Browne aaron0browne@gmail.com

This EIP thing is quickly becoming a priority, because these bugs would have been caught in the previous branch if the deploy had gotten past step 1. I think I can do a manual version update in AWS to test these fixes on a running instance, once the image gets built and pushed. I'll report the results.

### CODE REVIEW

**Comment by gracecodes144** [comment]
OK, this is getting into THE WEEDS. I'm having two problems:
1. The BUILD_NUM environment variable is not accessible in the docker build context, so the application binary in the resulting docker image does not know the full version number.
2. The application binary in the running docker container is trying to look for assets at the location they exist **on the host**. Huh?

I tried to solve both of these problems with the [`--build-arg`](https://docs.docker.com/engine/reference/commandline/build/) flag to docker build, but apparently this feature is too new to be in the CircleCI docker version.

I'm at least clear on why the first issue is happening, but the second issue is a little bit baffling. Obviously the file path is getting cached in a weird way, possibly in the `bindata.go` processes (help, @bruth)? Either way, it's far too late on a Friday for me to effectively solve these issues. I'll pick up next week. Error output from the running container in the latest CircleCI build is:

```
Cloning into '/opt/repos/github.com/chop-dbhi/data-models'...
2016/03/04 20:53:31 http: panic serving 172.17.42.1:42342: Asset assets/index.md can't read by error: Error reading asset assets/index.md at /home/ubuntu/.go_project/src/github.com/chop-dbhi/data-models-service/assets/index.md: open /home/ubuntu/.go_project/src/github.com/chop-dbhi/data-models-service/assets/index.md: no such file or directory
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc82060e300)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x828640, 0xc820671840)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
main.loadTemplate(0x8e06b0, 0xf, 0xc8204ea120)
    /go/src/app/render.go:28 +0xa6
main.renderMarkdown(0x7fc570ee6028, 0xc8204cf3b0, 0x8e06b0, 0xf, 0x78fd60, 0xc820595c20)
    /go/src/app/render.go:35 +0x2b
main.RenderIndexHTML(0x7fc570f094c0, 0xc82063e340)
    /go/src/app/render.go:80 +0x165
main.httpIndex(0x7fc570f09410, 0xc82063e340, 0xc8200c1ce0, 0x0, 0x0, 0x0)
    /go/src/app/http.go:89 +0xf0
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc82004ea40, 0x7fc570f09410, 0xc82063e340, 0xc8200c1ce0)
    /go/src/github.com/julienschmidt/httprouter/router.go:344 +0x195
github.com/rs/cors.(*Cors).Handler.func1(0x7fc570f09410, 0xc82063e340, 0xc8200c1ce0)
    /go/src/github.com/rs/cors/cors.go:188 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc8200b4980, 0x7fc570f09410, 0xc82063e340, 0xc8200c1ce0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc82000c700, 0x7fc570f09410, 0xc82063e340, 0xc8200c1ce0)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82060e300)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by gracecodes144** [comment]
I think we should use vendoring, build a statically linked binary, and then package that binary into a tiny little docker image without trying to rebuild inside the docker image. /noteformyself

**Comment by bruth** [comment]
Agreed. I've been meaning to do this across the board as well. We will write up the convention to follow and do it.

**Comment by bruth** [comment]
[Glide](https://glide.sh/) has been the vendoring solution that has resonated with me the most.

**Comment by gracecodes144** [comment]
OK, well the tests passed until the deployment stage, which failed because branch deployments are over the EIP limit. I manually deployed this application version (image pulled from docker hub) in the development AWS environment and it is working. So, if you're OK with these changes, @bruth, we can merge into master which will trigger an auto-deploy to the development environment and then once we increment to a final version it will auto-deploy to the production AWS environment.

**Comment by bruth** [comment]
I presume this is now moot.

**Pull request closed without merging**
