### PR TITLE
Attempt at ReverseProxied middleware

### PR DESCRIPTION
**Pull request by gracecodes144**
Following pattern from http://flask.pocoo.org/snippets/35/
and https://github.com/gorilla/handlers/blob/master/proxy_headers.go#L41

Signed-off-by: Aaron Browne aaron0browne@gmail.com

### CODE REVIEW

**Comment by gracecodes144** [comment]
Just some thoughts on a middleware solution. Getting an odd error when I test on the server that I don't understand:

```
2015/12/10 17:18:12 http: panic serving 172.17.0.16:43001: runtime error: invalid memory address or nil pointer dereference
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc8200ce630, 0x7f1e2735c028, 0xc8200be050)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
main.httpModels(0x7f1e29191ad8, 0xc8200ce6e0, 0xc8200d4700, 0x0, 0x0, 0x0)
    /go/src/app/http.go:103 +0x468
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc820014a80, 0x7f1e29191ad8, 0xc8200ce6e0, 0xc8200d4700)
    /go/src/github.com/julienschmidt/httprouter/router.go:299 +0x193
main.ReverseProxied.ServeHTTP(0x7f1e29190630, 0xc820014a80, 0x7f1e29191ad8, 0xc8200ce6e0, 0xc8200d4700)
    /go/src/app/http.go:361 +0x4df
main.(*ReverseProxied).ServeHTTP(0xc820017490, 0x7f1e29191ad8, 0xc8200ce6e0, 0xc8200d4700)
    <autogenerated>:9 +0xb6
net/http.serverHandler.ServeHTTP(0xc82000e720, 0x7f1e29191ad8, 0xc8200ce6e0, 0xc8200d4700)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ce630)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6
```

**Comment by gracecodes144** [comment]
Obviously this will not solve the client-side problems, but I was hoping it would at least fix the routing...

**Comment by bruth** [comment]
Remove the bindata.go file from this PR as it is not relevant.

**Comment by bruth** [comment]
Works without changes. Redirect is done at nginx level, so the auto-redirect by the service never occurs. `$http_host` is used to ensure the redirect occurs using the client set `Host` (more Docker safe..).

``` nginx
server {
    listen       80;
    server_name  localhost;

    # Trim trailing slash and redirect.
    rewrite ^/datamodels/(.*)/$ http://$http_host/datamodels/$1 permanent;

    location /datamodels/ {
        proxy_redirect off;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass http://datamodels:8123/;
    }

    # ...
}
```

**Comment by gracecodes144** [comment]
I'm going to use `$proxy_add_x_forwarded_for` instead of `$remote_addr` because it seems more general, based on the very last section of [this doc](http://nginx.org/en/docs/http/ngx_http_proxy_module.html), in cases where proxies might be chained. But other than that, I'll test the nginx config you've posted.

**Comment by bruth** [comment]
Updated to replace links dynamically..

``` nginx
server {
    listen       80;
    server_name  localhost;

    # Trim trailing slash and redirect.
    rewrite ^/datamodels/(.*)/$ http://$http_host/datamodels/$1 permanent;

    location /datamodels/ {
        # Replace all occurrences
        sub_filter_once off;

        sub_filter '<link href="/'  '<link href="/datamodels/';
        sub_filter '<a href="/'  '<a href="/datamodels/';
        sub_filter '<img src="/' '<img src="/datamodels/';
        sub_filter '<script src="/' '<script src="/datamodels/';

        sub_filter "<link href='/"  "<link href='/datamodels/";
        sub_filter "<a href='/"  "<a href='/datamodels/";
        sub_filter "<img src='/" "<img src='/datamodels/";
        sub_filter "<script src='/" "<script src='/datamodels/";

        sub_filter "<a class='brand' href='/'"  "<a class='brand' href='/datamodels/'";

        proxy_redirect off;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $remote_addr;

        proxy_pass http://datamodels:8123/;
    }

    # ...
}
```

**Comment by gracecodes144** [comment]
This is working. Closing the PR and deleting the branch.

**Pull request closed without merging**
